### ISSUE TITLE
coq 8.6. support

### ISSUE THREAD

**Issue by vzaliva** [math-classes/math-classes#25]
Currently Coq v8.6 is not supported. I see v8.6 branch, last touched by @mattam82  in October. I tried to compile it, and it hangs on compiling `theory/adjunctions.v`.

**Comment by matej-kosik** [comment]
Hi Vadim, there is an ongoing effort to monitor compilability of math-classes. This is the latest result:

https://ci.inria.fr/coq/job/bench-math-classes/1067/console

We were able to compile math-classes (commit d091d65) with Coq v8.6 (commit 11bdfe8) so I find this report surprising, but maybe we made some mistake.

Do you think you can provide more details? What kind of Coq 8.6 did you try to use?
(if you installed it via OPAM, which Coq version exactly is that?
 if you compiled Coq v8.6 yourself, which Coq commit did you use?)

**Comment by matej-kosik** [comment]
Btw. I've noticed that when I try to install `math-classes.8.6.dev` via OPAM, the installation hangs. So if you are trying to do that, then I could probably confirm the problem.

**Comment by vzaliva** [comment]
I am sorry I double-checked today in a clean environment and it builds OK. Probably some sort of mis-configuration at my side.

Any plans to release an 8.6-compatible version via OPAM?

**Comment by vzaliva** [comment]
Anything I can do to help so v8.6 support will become available via OPAM?

**Comment by matej-kosik** [comment]
Technically, it's simple to do. Maybe you can ask the [maintainer](https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-math-classes/coq-math-classes.1.0.4/opam) whether he would be happy if you did it for him/you/all_of_us.

**Comment by vzaliva** [comment]
Copying @spitters

**Comment by spitters** [comment]
@vzaliva Looks like you already fixed it? Thanks!
https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-math-classes/coq-math-classes.1.0.4

**Comment by vzaliva** [comment]
Not really:

```
#=== ERROR while installing coq-math-classes.1.0.4 ============================#
# opam-version 1.2.2
# os           linux
# command      make -j4
# path         /home/lord/.opam/4.04.0.coq.8.6/build/coq-math-classes.1.0.4
# compiler     4.04.0
# exit-code    2
# env-file     /home/lord/.opam/4.04.0.coq.8.6/build/coq-math-classes.1.0.4/coq-math-classes-1908-c61e7b.env
# stdout-file  /home/lord/.opam/4.04.0.coq.8.6/build/coq-math-classes.1.0.4/coq-math-classes-1908-c61e7b.out
# stderr-file  /home/lord/.opam/4.04.0.coq.8.6/build/coq-math-classes.1.0.4/coq-math-classes-1908-c61e7b.err
### stdout ###
# [...]
# COQC misc/stdlib_hints.v
# COQC implementations/ne_list.v
# COQC misc/workaround_tactics.v
# COQC misc/JMrelation.v
# COQC quote/classquote.v
# COQC interfaces/canonical_names.v
# COQC misc/util.v
# COQC misc/propholds.v
# COQC misc/workarounds.v
# COQC misc/setoid_tactics.v
### stderr ###
# [...]
# File "./misc/setoid_tactics.v", line 1, characters 0-73:
# Warning: Notation _ = _ was already used in scope type_scope
# [notation-overridden,parsing]
# File "./misc/setoid_tactics.v", line 1, characters 0-73:
# Warning: Notation _ ≠ _ was already used in scope type_scope
# [notation-overridden,parsing]
# File "./misc/setoid_tactics.v", line 26, characters 30-31:
# Syntax error: '.' expected after [vernac:command] (in [vernac_aux]).
# make: *** [misc/setoid_tactics.vo] Error 1
# make: *** Waiting for unfinished jobs....

```

**Comment by vzaliva** [comment]
@spitters If you could make a new release via github based on v8.6 branch I can submit an update to OPAM package.

**Comment by spitters** [comment]
I just build this using coq 8.6 from opam.
https://github.com/math-classes/math-classes/tree/v8.6

Should the url in:
https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-math-classes/coq-math-classes.1.0.4/url
be changed to:
https://github.com/math-classes/math-classes/archive/v8.6.zip
?

**Comment by matej-kosik** [comment]
I think the safest way is to define a git-tag for the version of math-classes you just verified that it works with Coq 8.6. If you push this tag to github, github will automatically generate zip / tar.gz archive for you. Then you can reference that generated zip / tar.gz archive from the `url` file.

**Comment by spitters** [comment]
Isn't this what the 8.6 branch is supposed to do?
8.6 is supposed to compile with the stable 8.6.

**Comment by vzaliva** [comment]
@spitters changing URL to https://github.com/math-classes/math-classes/archive/v8.6.zip in OPAM package will work.  I did a quick check and this version compiles with 8.6 but does not compile with coq-8.5.

One option is to adjust version requirement for current package to coq <8.6, so people can still use it with 8.5. You will need to re-release it with the new version number like 1.0.5 for this change to propagate.

In parallel, you can release a new version, say 1.0.6 which requires coq >=8.6.

Depending on version of coq people will be able to install either 1.0.5 or 1.0.6.

**Comment by spitters** [comment]
Thanks!
https://github.com/coq/opam-coq-archive/pull/137

**Comment by vzaliva** [comment]
I have successfully installed coq-math-classes.1.0.6 with Coq-8.6 via opam. Thanks!
