### ISSUE TITLE
Anomaly: index to an anonymous variable.

### ISSUE THREAD

**Issue by vzaliva** [math-classes/math-classes#34]
After importing minmax, typeclass instance databse printing is broken:

```
Require Import MathClasses.orders.minmax.
Print HintDb typeclass_instances.

```

Anomaly: index to an anonymous variable. Please report at http://coq.inria.fr/bugs/.

**Comment by vzaliva** [comment]
Further investigation narrowed it down to the following definition in `MathClasses.interfaces.universal_algebra`:

```
    Print HintDb typeclass_instances.

    Global Instance eval_strong_proper {V} (n: OpType):
      Proper ((pointwise_dependent_relation (sorts σ) _
        (λ _, pointwise_relation V eq)) ==> eq ==> eq) (@eval V n).
    Proof with auto.
     intros x y E a _ [].
     unfold pointwise_dependent_relation in E.
     unfold pointwise_relation in E.
     induction a; simpl.
       apply E...
      congruence.
     reflexivity.
    Qed.

    Print HintDb typeclass_instances.

```

`Print HintDb` before this definition works, but it fails after it.

**Comment by vzaliva** [comment]
Since it is exposing Coq anomaly, I also reported in Coq bugzilla: https://coq.inria.fr/bugs/show_bug.cgi?id=5364

**Comment by vzaliva** [comment]
I checked with Coq 8.5.3 and no problem there. It is specific to 8.6

**Comment by spitters** [comment]
Thanks! Looks like this is still open:
https://coq.inria.fr/bugs/show_bug.cgi?id=5401

**Comment by Zimmi48** [comment]
This issue has been fixed in (Coq) master.

**Comment by spitters** [comment]
Great! Is there anything we change in the library?

**Comment by Zimmi48** [comment]
No, I think the issue can simply be closed.
